### ISSUE TITLE
template output configuration (when not using Ember) isn't working

### ISSUE THREAD

**Issue by dguzzo** [jimsynz/hamlbars#28] opened 2012-07-18 22:41 UTC
my initializer, **hamlbars.rb** has this:

``` ruby
if defined? Hamlbars
  Hamlbars::Template.template_destination = 'Handlebars.blah'
end
```

yet the compiled javascript (in the browser) results to this:

``` javascript
Handlebars.templates["product"] = Handlebars.compile("testtest");
```

(the 'testtest' string is a good sign, as my products.js.hamlbars template and its content is being loaded properly)

i did some digging around in the hamlbars gem source itself with a colleague, and we couldn't figure out why the override wasn't working. though it does look like **@template_destination** never gets used in **template.rb**.

**Comment by jimsynz** [comment] 2012-07-20 04:15
I know, it's weird. It happens to me too, but I don't have time to fix it (I just started a new job), so in the mean time try:

``` ruby
Hamlbars::Template.render_templates_for :ember if defined? Hamlbars
```

Let me know if that works for you.

**Comment by dguzzo** [comment] 2012-07-21 02:32
Thanks for the response, James. I definitely understand about not having enough time. Perhaps I'll try to find the bug and fix it, although I'm still relatively new to Ruby and usually don't muck around in gem internals but rather stay up at the Rails level.

As for your suggestion, that would only work if using Ember, right? We're already using Backbone on the project in question, as well as a number of other libraries, so adding Ember on top of it all is something I'd like to avoid.

**Comment by jimsynz** [comment] 2012-07-21 02:33
Oh sorry, I misunderstood. Usually people are asking to change the template configuration to make it fit for ember :) 

## 

James Harton
sociable.co.nz
@jamesotron
+64226803869

**Comment by jimsynz** [comment] 2012-11-06 04:10
Can you try using the v2.0 branch in conjunction with the handlebars_assets gem? In v2.0 I've completely removed all compilation code from Hamlbars and it just outputs straight up handlebars templates, meaning you can use another gem like handlebars_assets to do the compilation you need.

**Comment by brutuscat** [comment] 2012-11-12 15:40
@jamesotron how to configure rails pipeline so that handlebars_assets picks up the output of hamlbars and the templates gets compiled in the server side?

**Comment by jimsynz** [comment] 2012-11-12 19:54
Easiest way is to just chain the file extensions, so your template would be renamed from `mytemplate.js.hamlbars` to mytemplate.js.hbs.hamlbars` - I've just double checked, and this works without any server config in a fresh Rails install with these two gems installed.

**Comment by brutuscat** [comment] 2012-11-12 20:46
Interesting... Actually now I removed hamlbars and I'm using plain haml. For me this >

```
.alert.fade.in{:class => "alert-{{type}}"}
  %button.close{{"data-dismiss" => "alert"}} &times;
  {{message}}
```

is better than trying to adapt haml usin `hb` helper

Why do you think it is better to use hamlbars?

Thanks!

**Comment by jimsynz** [comment] 2012-11-12 20:50
I find the `hb` helper to be a little easier for things like hash arguments, etc. I'd like to figure out a nice way to add a new expression type to haml, but haven't figured that out yet :)

**Comment by thepixelmonk** [comment] 2012-12-12 07:08
Having a similar issue, it's just spitting out

`Handlebars.templates["templates/conversations"] = Handlebars.compile("hi");`

Guess handlebars_assets isn't picking it up or something. Not sure what the issue is. I've chained the extensions.

**Comment by jimsynz** [comment] 2012-12-12 21:06
Closing because compilation has been removed from the v2.0 branch.

**Closed as completed by jimsynz** 2012-12-12 21:06 UTC
